### ISSUE TITLE
Visualization of Point Cloud Results

### ISSUE THREAD

**Issue by B1nna** [miniflash/SQFI#1]
Hi，thank you for opening up this code.  When I evaluate and save the .ply visualization results, the point cloud is only a very small part of the room (a small block, especially in scannet dataset) and extremely sparse. May I ask how you save the results and display them in your paper? Can you share that part of the code? Thank you very much!!

**Comment by miniflash** [comment]
Actually, I also encountered the same problem and adopted a less concise method. The process is to increase the test episodes as much as possible, and according to the relationship during data processing, pass all the prediction results of ".ply" back to the original room. Then you can get the visualization results. But to record the data relationship in the process, this part of the code makes the project look very untidy, it does not appear in the open code.

**Comment by jxy0601** [comment]
Thank you for opening up your code for research. I notice that you show some nice visualizations of the results of your paper. Can you share that part of the code? If it's not public, can you share it by email so I can learn? Thank you very much!
