### ISSUE TITLE
About the code of visualization 

### ISSUE THREAD

**Issue by B1nna** [miniflash/SQFI#2]
Hello, thank you very much for opening up this very meaningful code. It has been about two months since I last asked you about the visualization of results. Unfortunately, I have spent the past month researching its visualization and encountered some difficulties and have not been able to implement the visualization well.
      Therefore, I would like to request if you could share your part of the code about visualization with me for my learning and reference? If possible, I would greatly appreciate it if you could send it to my email:  liu815555@163.com   If not, I can also understand. Anyway, thank you very much and I love you！！!

**Comment by jxy0601** [comment]
Do you have a visualisation now? I can only visualise a small part, I don't know if you have a good way? @B1nna

**Comment by B1nna** [comment]
> Do you have a visualisation now? I can only visualise a small part, I don't know if you have a good way? @B1nna

sry ，I don not have a good way to visualise. My results are so sparse that it's impossible to distinguish what it is. May I ask if you are willing to share your code with me via email so that I can learn and find better ways to visualize larger areas? Thank you very much！@jxy0601
